# Generated by Django 4.0 on 2022-02-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
