# Generated by Django 4.0 on 2022-02-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='SOME STRING', max_length=20000),
        ),
    ]
